[tools]
claude = "latest"
gemini = "latest"
jq = "latest"
neovim = "latest"
node = "latest"
pandoc = "latest"
tmux = "latest"

[tasks.restart-alsa]
description = "Restart ALSA to fix the audio output issue"
run = "sudo alsa force-reload"
